{% set name = "POT" %}
{% set version = "0.4.0" %}
{% set build = 0 %}
{% set sha256 = "1f61f82bebdcb5e01286da0778b6219feb2b99b82cf234b0712fbb7d09d912ef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - cython
    - numpy 1.9.*   # [not (win and py36)]
    - numpy 1.11.*  # [win and py36]
  run:
    - python
    - numpy >=1.9   # [not (win and py36)]
    - numpy >=1.11  # [win and py36]
    - scipy
    - matplotlib

test:
  imports:
    - ot
  requirements:
    - numpy

about:
  home: http://github.com/rflamary/POT
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python Optimal Transport library'
  description: |
    This open source Python library provide several solvers for optimization
    problems related to Optimal Transport for signal, image processing and
    machine learning.
  doc_url: http://pot.readthedocs.io/
  dev_url: https://github.com/rflamary/pot

extra:
  recipe-maintainers:
    - dougalsutherland
