{% set name = "POT" %}
{% set version = "0.7.0" %}
{% set build = 1 %}
{% set sha256 = "d4ac2bc8791f049a3166820d51e218d6c299885449b735eafef8d18c76d4ad06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - install-reqs.patch  # https://github.com/PythonOT/POT/pull/174
    - remove-cc-setting.patch  # https://github.com/PythonOT/POT/pull/175

build:
  number: {{ build }}
  script:
    - export POT_LEAVE_CC=true  # [unix]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.23
    - numpy 1.16
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0
    - matplotlib-base >=1.5

test:
  imports:
    - ot

about:
  home: http://github.com/PythonOT/POT
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Optimal Transport library
  description: |
    This open source Python library provide several solvers for optimization
    problems related to Optimal Transport for signal, image processing and
    machine learning.
  doc_url: http://pot.readthedocs.io/
  dev_url: https://github.com/PythonOT/POT

extra:
  recipe-maintainers:
    - djsutherland
    - rflamary
