# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HFMgkPkv75TkipfijuPkT234sTwd278ZLS31ppr4af3PY/W13Fl4REShCHRAywy8nZH05533uNIfBn4+i4yJlN6aKo0BGNRHstlZkwkwuBeUYG8wmcLVylXv82VrMwFaVX2LVZJnfAJrtuQwEXLd0KpGgQhXV38qN0yMFOlSkvu5Q16ERMrxpBD7oaBWKsbrxhT/zHwERv7LPQHQYQajcPrOMyK3y2nG1MzEDzApqdxL3/4x11PROXrSiOb0Ad0zS/HoIrSsVja2+VvnhMN1IASygNVvrV20sTIMDO9uF90+EJ/3MJFdWzuBorXtS6JVkOGZLNQwRVex8fgZNRKEJXCM7cYYNeV+6yFmQ3VCYWqb9Zs8mb19/Dczy6pV2u3Ro98d9Sfq5H9Dguz2L+CU/3iUOUnLUtavThhR0gz2qrXyE4aRnetWXvd0RsRUMO0QSPj5/tz31SvKIuc7kkMIcb2DD8oSh7x6/8YJsQLbROZkqMwJPtLU/7ITriNPwG22audzIw2uqalVhW2jpYBRCxZ12Ck8fOLAn1r6gl2xf4F8J2skloSRCRM02yJblNctZ73BzIMwrBWgcsuAxH/m58OTVL4dmGgVsbbK7E47dqFUvdWJwCASyySuZW8kJlkXfpFvYQOpqpksGt2BEqjSmNWDOOGP8ILbC3wcs8CdMOg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
