appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: tbFFDnWk81nRiO5H1wUTqvO44vNohrpC0jfJ8fD4ofAF/ova/PuEG7d7AaYoZ9+2DsX71CRrVbGQ4fweWG+GXWlAlpJGuocegkJWYM6230Du1o8ur0XcAUNNXLJXimRQliigGzWSTiUopWSuaCw7BH0Kdj8R9FHSZ2Q6wqDxhjRjFn34GsDI002J3qObC+8bL69SYOcsyq+HOr6rDYS+S5URXFJJ6hGgYlvzy8B/XR15p0Rl9X9IIFYbyZd6tUmleS8iOhF9Z1lDgOZIUCmeHFWmOBOE97c+qt1aasSjFZjewv9Zn3lXmwb1tUlkAKJjSGCwZn8giaXqfsORmA53iA05d7N+KqzYl5hAfnZAGHo7DmCe8yFnnYgSYxTokA1LlnrhqgFD1Hsuc/ZjkcpOaKz2EWeT194PJ5fXLKUco382pqPWuPMZpTKYg/6VyzWB9MJJXE8Twncvtbe8lsv63ZxXZEPkr3i4qlTztMu7J1ea51oMO017+O2FtXXA6v1NVqn10ZfiRAjiTwAqRjplTGn8LLvKSgELVjNNNuV2J6wvchDL9jjB88r6WL+xQQUaquTD50irQlnoOwSc6VWR0oDLEsNx7mfm1k4r3Umlh2TqzYds9t+J5fKE35xdCQAkumAO4mBvkx4j4QAX69mSCdiDlR6/5sX7rnJ+xdN2Me8=}
provider:
  win: azure
conda_forge_output_validation: true
