travis:
  secure:
    BINSTAR_TOKEN: 0TZWBtuq2CJno6lSokNbqHp54O8+NCPX5ubfKMKCoTR7q+DWCzEBODreAc9wPfZculoTSWpqvW2+Dby3JX3KWiYxaOoNMcU0ll5NrM6QKpeixi0zk2u+MAvVGAmzyS9hAxvMl64dm6Dgxj2IzajJEGWreFY+DO9Y7Y4iI9SQ0jdZGCPQdWFmIh5HR0kOYMFUJcxZkF/hUvrdf1/a69ShZb3nz/rrT2oZ/G0DoG4ho3RpWfkZkayRztifKQr/Xncoqi+hyu39nhFoZobKjjotAqFmBskU5CW28QW5zOHZzNC03fcxYWzlBVWnGSKjwyP0LdV5oZKnfY1FU2YOKlQMszWdziUGav6bX5qWXIX9mMjHsNEn+d81EnJdbvc4sYyDBbb7zUNMxqlyAKz9hSAs3empM25LG3tIR5CxxOZN4ofinEqfJzJwWKwClGwBUkSadaq/thiknWkOUYXe29eqo3oQf/tOu3BSXBcJz08sNUVs/3dgme+M5oCdX1IKaWe+EDfNb+7nkC/bbfl64JPYoJryWE3eAr+i7cwcni/E4w95vvURl4kiMZYKBGYVKA7ceBIGlkY0oYAW0z9WRNq9bxrDd9pAKV9USU8n66rQp/oAsat9mjmU2LIg3ycMT/cWB33wMh/H5lLvydjXZKbPyDPLfcbZEXIxCSzfsMaPdNM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
