travis:
  secure:
    BINSTAR_TOKEN: HFMgkPkv75TkipfijuPkT234sTwd278ZLS31ppr4af3PY/W13Fl4REShCHRAywy8nZH05533uNIfBn4+i4yJlN6aKo0BGNRHstlZkwkwuBeUYG8wmcLVylXv82VrMwFaVX2LVZJnfAJrtuQwEXLd0KpGgQhXV38qN0yMFOlSkvu5Q16ERMrxpBD7oaBWKsbrxhT/zHwERv7LPQHQYQajcPrOMyK3y2nG1MzEDzApqdxL3/4x11PROXrSiOb0Ad0zS/HoIrSsVja2+VvnhMN1IASygNVvrV20sTIMDO9uF90+EJ/3MJFdWzuBorXtS6JVkOGZLNQwRVex8fgZNRKEJXCM7cYYNeV+6yFmQ3VCYWqb9Zs8mb19/Dczy6pV2u3Ro98d9Sfq5H9Dguz2L+CU/3iUOUnLUtavThhR0gz2qrXyE4aRnetWXvd0RsRUMO0QSPj5/tz31SvKIuc7kkMIcb2DD8oSh7x6/8YJsQLbROZkqMwJPtLU/7ITriNPwG22audzIw2uqalVhW2jpYBRCxZ12Ck8fOLAn1r6gl2xf4F8J2skloSRCRM02yJblNctZ73BzIMwrBWgcsuAxH/m58OTVL4dmGgVsbbK7E47dqFUvdWJwCASyySuZW8kJlkXfpFvYQOpqpksGt2BEqjSmNWDOOGP8ILbC3wcs8CdMOg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
